language: php

php:
  - 5.5
  - 5.4

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'
    - DOCROOT='/var/www'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update
  - pear channel-discover pear.drush.org
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo a2enmod rewrite
  - sudo cp -f tests/travis-ci-apache /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - pear install drush/drush
  - phpenv rehash
  - cd $TRAVIS_BUILD_DIR
  - export MODULE=$(basename $(pwd))
  - export MODULE_DIR=$DOCROOT/sites/all/modules/$MODULE
  - sudo chmod -R 777 /var
  - drush dl drupal --destination=/var --drupal-project-rename=www --yes
  - drush si --db-url="mysql://$DB_USERNAME@127.0.0.1/$DATABASE" -r $DOCROOT --yes
  - ln -s $TRAVIS_BUILD_DIR $MODULE_DIR
  - cd $TRAVIS_BUILD_DIR/..
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - java -jar selenium-server-standalone-2.42.2.jar > /dev/null &
  
before_script:
  - cd $MODULE_DIR/tests
  - cp behat.yml.dist behat.yml
  - composer install
  - bin/behat features/travis-ci.feature

script:
  - cd $MODULE_DIR/tests
  - bin/behat --tags="~travis&&~live&&~permissions&&~uninstall"
