# Schema for the marketo_ma.settings configuration.
marketo_ma.settings:
  type: config_object
  label: 'Marketo MA configuration'
  mapping:
    instance_host:
      type: string
      label: 'Marketo Instance Host'
    logging:
      type: integer
    tracking_method:
      type: string
    munchkin:
      type: config_object
      label: 'Munchkin Javascript API'
      mapping:
        javascript_library:
          type: string
        api_private_key:
          type: string
        partition:
          type: string
        lead_source:
          type: string
        account_id:
          type: string
    rest:
      type: config_object
      label: 'REST API config'
      mapping:
        batch_requests:
          type: integer
        client_id:
          type: string
        client_secret:
          type: string
    field:
      type: config_object
      label: 'Field Definition config'
      mapping:
        enabled_fields:
          type: sequence
          label: 'Enabled marketo fields'
          sequence:
            type: integer
            label: 'Marketo field ID'
    tracking:
      type: config_object
      label: 'Field Definition config'
      mapping:
        request_path:
          type: config_object
          mapping:
            mode:
              type: integer
              label: 'Add tracking to specific pages'
            pages:
              type: string
              label: 'Pages by their paths'
        user_role:
          type: config_object
          mapping:
            mode:
              type: integer
              label: 'Add tracking for specific roles'
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
